# Server
server.port=8080

## H2 (dev) — swap for MySQL in production
#spring.datasource.url=jdbc:h2:mem:riskguard;DB_CLOSE_DELAY=-1
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

## JPA
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MySQL (production — uncomment and fill)
# spring.datasource.url=jdbc:mysql://localhost:3306/riskguard
# spring.datasource.username=root
# spring.datasource.password=yourpassword
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



// supabase plsql databse connection
spring.datasource.url=jdbc:postgresql://db.sseslbamwfqlxiqfdbwc.supabase.co:5432/postgres?user=postgres&password=Vaibhav@2511910921
spring.datasource.username=postgres
spring.datasource.password=Vaibhav@2511910921
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


rozarpay_test_key=rzp_test_SfitmtfFH9SX9K
rozatpay_test_secret=2aeDNLvK9gxtNPhNfe7BCkZB

database_password=kt3$b4EqJ#a+Pix